name: Build and Pack

on:
  push:
    branches: [ main, V*, develop ]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

  package:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the build job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Package Project
      run: dotnet pack --configuration Release /p:PackageVersion=0.0.0-PRCheck --output ./artifacts
