name: Build & Pack Check

on:
  push:
    branches: [ main, V*, develop ]
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: NuGet package Package
      run: dotnet pack --configuration Release /p:PackageVersion=0.0.0-PRCheck --output ./artifacts
