name: Publish NuGet Package

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Match your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Print API Key for Debugging
        run: echo "API Key: ${{ secrets.NUGET_API_KEY }}"  # This will print the API key to debug. Be cautious about exposing sensitive data.
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish NuGet package
        run: |
          echo "Publishing NuGet package..."
          dotnet nuget push ./nupkg/*.nupkg --source 'nuget.org' --api-key ${{ secrets.NUGET_API_KEY }}
